AUDIT   2022/11/04 14:06:53 [Workflow:workflow] Starting workflow (Writing log to log/scipipe-20221104-140653-workflow.log)
AUDIT   2022/11/04 14:06:53 [Task:index] Output file already exists, so skipping: ref.mmi
AUDIT   2022/11/04 14:06:53 [Task:alignment] Output file already exists, so skipping: output/alignment.sam
AUDIT   2022/11/04 14:06:53 [Task:samtools] Output file already exists, so skipping: output/result.txt
AUDIT   2022/11/04 14:06:53 [Task:parse] Executing: python3 ../input/parser.py ../output/result.txt.txt > output/parsed.txt
ERROR   2022/11/04 14:06:53 [Task:parse] Command failed!
Command:
python3 ../input/parser.py ../output/result.txt.txt > output/parsed.txt

Output:
Traceback (most recent call last):
  File "../input/parser.py", line 20, in <module>
    f = open(name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '../output/result.txt.txt'

Original error:exit status 1


